//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sozlukv5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fkullanici
    {
        public int id { get; set; }
        public string girilenDil { get; set; }
        public string eklenenKelime { get; set; }
        public string aciklama { get; set; }
    }
}
